---
name: Criterion

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install criterion
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-criterion
          version: 1.0.0-alpha3
          use-tool-cache: true
      - name: Run criterion
        uses: actions-rs/cargo@v1
        with:
          command: criterion
      - name: Upload criterion reports
        uses: actions/upload-artifact@v2
        with:
          name: target-criterion
          path: target/criterion
