---
name: Criterion

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run criterion for baseline 
        working-directory: ./benchmark
        run: git checkout HEAD^ && cargo bench -- --verbose --save-baseline previous
      - name: Run criterion on new commit
        working-directory: ./benchmark
        run: git checkout - && cargo bench -- --verbose --baseline previous
      - name: Upload criterion reports
        uses: actions/upload-artifact@v2
        with:
          name: target-criterion
          path: target/criterion
